<!-- <div id="react-chat"></div>
<script src="Aprilo_Chatbot::react-chat/js/maincc1827a2.js"></script>
<link rel="stylesheet" href="Aprilo_Chatbot::react-chat/css/maina03325b6.css" /> -->
<div id="react-chat"></div>
<script src="<?php echo $block->getViewFileUrl('Aprilo_Chatbot::react-chat/static/js/main.js'); ?>"></script>
<link rel="stylesheet" href="<?php echo $block->getViewFileUrl('Aprilo_Chatbot::react-chat/static/css/main.css'); ?>" />
