<form action="<?= $block->getUrl('chatbot/import/upload') ?>"
    method="post"
    enctype="multipart/form-data"
    id="csv-upload-product-form">
    <?= $block->getBlockHtml('formkey') ?>
    <fieldset class="admin__fieldset">
        <legend class="admin__legend"><?= __('Upload CSV File For Product') ?></legend>
        <div class="admin__field">
            <label class="admin__field-label">Select CSV:</label>
            <div class="admin__field-control">
                <input type="file" name="csv_file_product" accept=".csv" class="admin__control-file" required />
                <a href="<?= $block->getViewFileUrl('Aprilo_Chatbot::sample_file/sample_product.csv') ?>"
                    class="admin__button">Download Sample File</a>
            </div>
        </div>
        <div class="admin__field upload">
            <button type="submit" class="admin__button-primary" id="upload-btn-product"><?= __('Upload and Process CSV') ?></button>
        </div>
    </fieldset>
</form>

<script>
    require(['jquery'], function($) {
        $(document).ready(function() {
            $('#csv-upload-product-form').on('submit', function() {
                $('body').trigger('processStart');
                if ($('#upload-btn-product').prop('disabled')) {
                    e.preventDefault(); // Prevent multiple submissions
                    return false;
                }
                // Disable the button
                $('#upload-btn-product').prop('disabled', true).text('Processing...');
            });
        });
    });
</script>



